remote_theme: ys1998/academic-portfolio
# remote_theme: chrisrhymes/bulma-clean-theme

# remote_theme: benbalter/retlab
# remote_theme: adobe/hyde-theme@v1.0.0

############################################
# theme: jekyll-theme-Cayman
# title: [Jimmy Doi Github Page]
# description: []
############################################
# theme: jekyll-theme-Cayman
# theme: jekyll-theme-Minimal
