remote_theme: adobe/hyde-theme@v1.0.0
# remote_theme: benbalter/retlab

# remote_theme: chrisrhymes/bulma-clean-theme

############################################
# theme: jekyll-theme-Cayman
# title: [Jimmy Doi Github Page]
# description: []
############################################
# theme: jekyll-theme-Cayman
# theme: jekyll-theme-Minimal
